version: "3"
services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./logs:/logs
    links:
      - "opensearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "5140:5140"
      - "5140:5140/udp"
      - "5141:5141"

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - "discovery.type=single-node"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "plugins.security.disabled=true"
    expose:
      - "9200"
    ports:
      - "9200:9200"
      - "9600:9600"

  opensearch-dashboard:
    image: opensearchproject/opensearch-dashboards:latest
    links:
      - "opensearch"
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
      - "opensearch.ssl.verificationMode=none"
